import Head from "next/head";
import Link from "next/link";
import React from "react";

import Container from "react-bootstrap/Container";

import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";

function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>WeeaBoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar expand="lg">
        <Container>
          <Navbar.Brand className="logo text-white" href="#">
            Anime List.
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="navbarScroll" bg="light" />
          <Navbar.Collapse id="navbarScroll">
            <Nav
              className="me-auto my-2 my-lg-0"
              style={{ maxHeight: "100px" }}
              navbarScroll
            >
              <Link href="/" className="mx-3 text-white navbar-link">
                Home
              </Link>
              <Link href="/manga" className="mx-3 text-white navbar-link">
                Manga
              </Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <main>
        <Container>{children}</Container>
      </main>
    </div>
  );
}

export default Layout;
